[project]
name = "Personal-Finance-Tracker"
version = "0.1.0"
description = "Streamlit personal finance app"
dependencies = [
    "pandas>=2.2.3",
    "plotly>=6.0.0",
    "streamlit>=1.42.1",
    "uvicorn>=0.34.0",
]

